### PR TITLE
add meta community Rheinufer

### PR DESCRIPTION
**Pull request by pberndro**
Rheinufer is a meta community from Freifunk Rheinland e.V.

### CODE REVIEW

**Comment by phoet** [comment]
:eyes: thx

**Comment by phoet** [comment]
@pberndro do you have access to the provided data? looks like at least one node has bad geo data:

```
        {
            "clientcount": 0,
            "firmware": "2014.4-beta-4",
            "flags": {
                "client": false,
                "gateway": false,
                "online": true
            },
            "geo": [
                50992845.0,
                5929452.0
            ],
            "id": "64:66:b3:33:c4:e4",
            "macs": "66:6a:b3:33:c4:e4, 64:66:b3:33:c4:e4",
            "name": "Selfkant3"
        },
```

the decimal point is at the wrong place i guess

**Comment by pberndro** [comment]
Sorry for my delay ;-).
There have been several attempts to find the owner. Unfortunately, without success.
https://mailman.freifunk-rheinland.net/pipermail/ffrl/2014-September/003792.html

Is there currently a filter in your app to remove such bad data?
I think this would make sense, because many people can't correctly enter their coordinates.
Please don't ask me why... ;-) .

**Comment by phoet** [comment]
@pberndro i added a filter for proper degrees in geo data in the latest version. the next version will consume a different api endpoint anyways.

**Pull request merged**
